# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(505, 289)
        settings.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox = QtWidgets.QGroupBox(settings)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 241))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 211, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.static_set_dailyGoals = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.static_set_dailyGoals.setObjectName("static_set_dailyGoals")
        self.horizontalLayout.addWidget(self.static_set_dailyGoals)
        self.LE_set_dailyGoals = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LE_set_dailyGoals.setObjectName("LE_set_dailyGoals")
        self.horizontalLayout.addWidget(self.LE_set_dailyGoals)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.static_set_speedUpdate = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.static_set_speedUpdate.sizePolicy().hasHeightForWidth())
        self.static_set_speedUpdate.setSizePolicy(sizePolicy)
        self.static_set_speedUpdate.setObjectName("static_set_speedUpdate")
        self.horizontalLayout_2.addWidget(self.static_set_speedUpdate)
        self.LE_set_speedUpdate = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_set_speedUpdate.sizePolicy().hasHeightForWidth())
        self.LE_set_speedUpdate.setSizePolicy(sizePolicy)
        self.LE_set_speedUpdate.setObjectName("LE_set_speedUpdate")
        self.LE_set_speedUpdate.addItem("")
        self.LE_set_speedUpdate.addItem("")
        self.LE_set_speedUpdate.addItem("")
        self.LE_set_speedUpdate.addItem("")
        self.LE_set_speedUpdate.addItem("")
        self.LE_set_speedUpdate.addItem("")
        self.LE_set_speedUpdate.addItem("")
        self.horizontalLayout_2.addWidget(self.LE_set_speedUpdate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(settings)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 10, 251, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.CB_set_showAD = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_set_showAD.setGeometry(QtCore.QRect(10, 20, 231, 16))
        self.CB_set_showAD.setObjectName("CB_set_showAD")
        self.CB_set_showProcess = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_set_showProcess.setGeometry(QtCore.QRect(10, 40, 231, 16))
        self.CB_set_showProcess.setObjectName("CB_set_showProcess")
        self.btn_save = QtWidgets.QPushButton(settings)
        self.btn_save.setGeometry(QtCore.QRect(140, 260, 75, 23))
        self.btn_save.setObjectName("btn_save")
        self.btn_cancel = QtWidgets.QPushButton(settings)
        self.btn_cancel.setGeometry(QtCore.QRect(290, 260, 75, 23))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(settings)
        self.LE_set_speedUpdate.setCurrentIndex(1)
        self.btn_save.clicked.connect(settings.set_save) # type: ignore
        self.btn_cancel.clicked.connect(settings.set_cancel) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Settings"))
        self.groupBox.setTitle(_translate("settings", "Normal Settings"))
        self.static_set_dailyGoals.setText(_translate("settings", "Daily Goals"))
        self.static_set_speedUpdate.setText(_translate("settings", "ISK Speed Update"))
        self.LE_set_speedUpdate.setItemText(0, _translate("settings", "Every 3mins"))
        self.LE_set_speedUpdate.setItemText(1, _translate("settings", "Every 5mins"))
        self.LE_set_speedUpdate.setItemText(2, _translate("settings", "Every 10mins"))
        self.LE_set_speedUpdate.setItemText(3, _translate("settings", "Every 15mins"))
        self.LE_set_speedUpdate.setItemText(4, _translate("settings", "Every 20mins"))
        self.LE_set_speedUpdate.setItemText(5, _translate("settings", "Every 30mins"))
        self.LE_set_speedUpdate.setItemText(6, _translate("settings", "Every hour"))
        self.groupBox_2.setTitle(_translate("settings", "Graphic"))
        self.CB_set_showAD.setText(_translate("settings", "Do not show corp AD on startup"))
        self.CB_set_showProcess.setText(_translate("settings", "Hide Process Bar"))
        self.btn_save.setText(_translate("settings", "Save"))
        self.btn_cancel.setText(_translate("settings", "Cancel"))
